const dataTema = [
    {
        id: "iman",
        tema: "Iman",
        deskripsi: "Hadits tentang iman",
        totalHadits: "18921",
        totalPages: "1893",
    },
    {
        id: "ilmu",
        tema: "Ilmu",
        deskripsi: "Hadits tentang ilmu",
        totalHadits: "11875",
        totalPages: "1188",
    },
    {
        id: "umat-terdahulu",
        tema: "Umat Terdahulu",
        deskripsi: "Hadits tentang umat terdahulu",
        totalHadits: "2865",
        totalPages: "287",
    },
    {
        id: "perjalanan-hidup",
        tema: "Perjalanan Hidup",
        deskripsi: "Hadits tentang perjalanan hidup",
        totalHadits: "17247",
        totalPages: "1725",
    },
    {
        id: "al-quran",
        tema: "Al-Quran",
        deskripsi: "Hadits tentang Al Quran",
        totalHadits: "5902",
        totalPages: "591",
    },
    {
        id: "akhlaq-dan-adab",
        tema: "Akhlaq dan Adab",
        deskripsi: "Hadits tentang akhlaq dan adab",
        totalHadits: "10996",
        totalPages: "1100",
    },
    {
        id: "ibadah",
        tema: "Ibadah",
        deskripsi: "Hadits tentang ibadah",
        totalHadits: "32847",
        totalPages: "3285",
    },
    {
        id: "makanan-minuman",
        tema: "Makanan Minuman",
        deskripsi: "Hadits tentang makanan minuman",
        totalHadits: "4295",
        totalPages: "430",
    },
    {
        id: "pakaian-perhiasan",
        tema: "Pakaian Perhiasan",
        deskripsi: "Hadits tentang pakaian perhiasan",
        totalHadits: "3505",
        totalPages: "351",
    },
    {
        id: "masalah-kepribadian",
        tema: "Masalah Kepribadian",
        deskripsi: "Hadits tentang masalah kepribadian",
        totalHadits: "5880",
        totalPages: "588",
    },
    {
        id: "muamalah",
        tema: "Muamalah",
        deskripsi: "Hadits tentang muamalah",
        totalHadits: "7479",
        totalPages: "748",
    },
    {
        id: "putusan-hukum",
        tema: "Putusan Hukum",
        deskripsi: "Hadits tentang putusan hukum",
        totalHadits: "3122",
        totalPages: "313",
    },
    {
        id: "kriminalitas",
        tema: "Kriminalitas",
        deskripsi: "Hadits tentang kriminalitas",
        totalHadits: "3604",
        totalPages: "361",
    },
    {
        id: "jihad",
        tema: "Jihad",
        deskripsi: "Hadits tentang jihad",
        totalHadits: "4506",
        totalPages: "451",
    },
];

export default dataTema;
